### ISSUE TITLE
Login Issues with PHP

### ISSUE THREAD

**Issue by subhakanta1979** [Himalayan-Academy/Saivite-Bible#25]
![image](https://user-images.githubusercontent.com/43493826/47029351-f28ec380-d188-11e8-937d-0fdcb4f1bd49.png)

Requesting Swamiji to raise a ticket to the SA/DBA of the Server to look into it.
Issue Description - The Login to the PHPMyADMIN on wiki.hindu.org runs into issues and only after multiple attempts of login the PHPMYADMIN page opens correctly. Please refer to the Screenshot.

Regards,
Subh

**Comment by subhakanta1979** [comment]
Session Timeout happens very frequently, please refer to the screenshot.

![image](https://user-images.githubusercontent.com/43493826/47029571-7f398180-d189-11e8-94e3-e9a9f411e5dd.png)

**Comment by Brahmanathaswami** [comment]
@subhakanta1979 

I am the SA/DBA for the server (smile)

Please confirm that you are not logged out in less than 24 minutes. 

Meanwhile I set the cookie session time out:

/etc/php5/cli/php.ini  
line 1461: session.gc_maxlifetime = 86400 
# that is one day; I don't want to keep in open for more that than

Let us see if that helps. Note PHP server cookies are set to last forever, so to get the new session timeout, you will need to delete the cookie for phpmyadmin in your browser.

 Otherwise you will get a 24 min time out.

see it that helps

**Comment by subhakanta1979** [comment]
Namaste Swamiji, I often get the below error with multiple attempts to Login to PHPMyADMIN.

![image](https://user-images.githubusercontent.com/43493826/47483494-086e4980-d857-11e8-9bb6-da50a19eb385.png)

**Comment by subhakanta1979** [comment]
I am not able to Login to PHPMYADMIN even after multiple attempts

**Comment by subhakanta1979** [comment]
Removed the Parameters from the URL and now I am able to Login.

**Comment by subhakanta1979** [comment]
Sure Swamiji Noted. I am closing this Ticket .
