### ISSUE TITLE
Please Resolve To One System

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Saivite-Bible#74]
Estimate time to fix: 1 hour

Code Igniter Can run severl applications on one system why do you have two, This make upgrade a nightmare, can you delete on and change the config in the admin to point to the same system folder?
![2019-03-17_15-42-12](https://user-images.githubusercontent.com/3675722/54501971-6a921e80-48cc-11e9-99c7-258015dfc159.png)

**Comment by subhakanta1979** [comment]
Namaste Acharyaji, Swamiji, Looked into it.

The initial design was to keep the UI separate from the Admin Panel, in fact the UI/Public View was never in the scope to begin with which is why the modules were developed asynchronously in two separate Codeigniter Folders. The application folder inside Admin is the back end, front end UI is the application folder outside, this is why we see two codeigniter system folders,
in order to make it one system folder I need more time and I need to do a regression testing so that it does not break the existing code. This is certainly not an one hour job.

Nevertheless It will not affect the upgrade , the library and the core files can be upgraded in both places.  ideally it should have been one system folder outside the Admin folder but now since it's been there from the beginning as the requirements were adhoc for both UI & The Admin Panel, to change it, is going to take some more time and it needs a thorough regression testing.

**Comment by Brahmanathaswami** [comment]
let it be for now....

**Comment by subhakanta1979** [comment]
Acknowledged. Work in Progress. As discussed earlier this is going to take more time.

Best Regards,
Subhakant

**Comment by Brahmanathaswami** [comment]
I deferred this issue, and assigned to myself, you should not spend anytime on it for now
